import { createTool } from "@anvia/core";
import { z } from "zod";

export function createCompileReportTool() {
  return createTool({
    name: "compileReport",
    description: "Formats and compiles Voluntary Carbon Market (VCM) research, ESG compliance benchmarks, and emissions audit findings into a structured, publication-ready Markdown intelligence report.",
    inputSchema: z.object({
      title: z.string().describe("The main title of the carbon intelligence or ESG compliance report"),
      summary: z.string().describe("An executive summary capturing core market benchmarks, carbon pricing, and regulatory findings"),
      sections: z.array(
        z.object({
          heading: z.string().describe("Section heading or topic name (e.g., 'Biochar Benchmarks', 'EU CBAM Scope 1-3 Compliance')"),
          content: z.string().describe("Detailed analysis, pricing data, compliance audit observations, or registry methodology details")
        })
      ).describe("List of structured body sections for the report"),
      keyTakeaways: z.array(z.string()).optional().describe("Bullet points highlighting key takeaways, price signals, or compliance action items"),
      sources: z.array(
        z.object({
          title: z.string().describe("Accredited registry or standard body title (e.g., 'Puro.earth CORC Index', 'Verra VCS')"),
          url: z.string().url().describe("Valid HTTP/HTTPS URL reference")
        })
      ).optional().describe("List of accredited standard body and registry citations"),
      disclaimer: z.string().optional().describe("Mandatory market disclaimer (e.g., 'Prices reflect voluntary carbon market benchmarks and are subject to market volatility.')")
    }),
    execute: async ({ title, summary, sections, keyTakeaways, sources, disclaimer }) => {
      const timestamp = new Date().toISOString().split("T")[0];

      let markdown = `# ${title}\n\n`;
      markdown += `*Generated by Carbon Scout on ${timestamp}*\n\n`;

      markdown += `## 📌 Executive Summary\n\n${summary}\n\n`;

      if (keyTakeaways && keyTakeaways.length > 0) {
        markdown += `## 💡 Key Takeaways\n\n`;
        for (const item of keyTakeaways) {
          markdown += `- ${item}\n`;
        }
        markdown += `\n`;
      }

      markdown += `## 🔍 Market Intelligence & Regulatory Analysis\n\n`;
      for (const section of sections) {
        markdown += `### ${section.heading}\n\n${section.content}\n\n`;
      }

      if (sources && sources.length > 0) {
        markdown += `## 📚 Accredited Sources & Registry Citations\n\n`;
        for (const source of sources) {
          markdown += `- [${source.title}](${source.url})\n`;
        }
        markdown += `\n`;
      }

      const activeDisclaimer = disclaimer ?? "Prices reflect voluntary carbon market benchmarks and are subject to market volatility.";
      markdown += `## ⚠️ Regulatory & Market Disclaimer\n\n> ${activeDisclaimer}\n\n`;
      markdown += `---\n*End of Report*\n`;

      return markdown;
    }
  });
}
